//footer
document.writeln(" <div class=\'new_foot\'>");
document.writeln(" 		<ul>");
document.writeln(" 			<li><a href=\'/\'>首页</a></li>");
document.writeln(" 			<li>|</li>");
document.writeln(" 			<li><a href=\'javascript:void(0)\' onclick=\'openZoosUrl();return false;\'>专家团队</a></li>");
document.writeln(" 			<li>|</li>");
document.writeln(" 			<li><a href=\'javascript:void(0)\' onclick=\'openZoosUrl();return false;\'>媒体报道</a></li>");
document.writeln(" 			<li>|</li>");
document.writeln(" 			<li><a href=\'javascript:void(0)\' onclick=\'openZoosUrl();return false;\'>真人案例</a></li>");
document.writeln(" 			<li>|</li>");
document.writeln(" 			<li><a href=\'javascript:void(0)\' onclick=\'openZoosUrl();return false;\'>网站地图</a></li>");
document.writeln(" 			<li>|</li>");
document.writeln(" 			<li><a href=\'javascript:void(0)\' onclick=\'openZoosUrl();return false;\'>最新文档</a></li>");
document.writeln(" 			<li>|</li>");
document.writeln(" 			<li><a href=\'javascript:void(0)\' onclick=\'openZoosUrl();return false;\'>在线咨询</a></li>");
document.writeln(" 			<li>|</li>");
document.writeln(" 			<li><a href=\'javascript:void(0)\' onclick=\'openZoosUrl();return false;\'>网络预约</a></li>");
document.writeln(" 			<li>|</li>");
document.writeln(" 			<li><a href=\'javascript:void(0)\' onclick=\'openZoosUrl();return false;\'>来院路线</a></li>");
document.writeln(" 		</ul>");
document.writeln(" 		<div class=\'newf_con\'>");
document.writeln(" 			<div class=\'f_logo\'>");
document.writeln(" 				<img src=\'/style/images/foot_logo.png\' alt=\'威海梨花\'>");
document.writeln(" 			</div>");
document.writeln(" 			<div class=\'f_hot\'>");
document.writeln(" 				<p>美丽热线：0631-5716999</p>");
document.writeln(" 				<p>专家咨询热线：0631-5717666</p>");
document.writeln(" 				<p>营业时间：8:00AM-6:00PM</p>");
document.writeln(" 				<p>鲁ICP备16040104号-1</p>");
document.writeln(" 				<p>地址：中国·威海市环翠区威高广场交通银行南侧三楼</p>");
document.writeln(" 				<p>网站内容申明：本网站信息仅供参考，不能作为诊疗及医疗依据，未经授权请勿复制及转载。</p>");
document.writeln(" 			</div>");
// document.writeln(" 			<div class=\'f_qr\'>");
// document.writeln(" 				<img src=\'/style/images/qr_03.png\' alt=\'威海梨花微信号\'>");
// document.writeln(" 			</div>");
document.writeln(" 		</div>");
document.writeln(" 	</div>");
document.writeln("</div> ");