//header
document.writeln("<div class=\'header\' id=\'header\'> ");
document.writeln("	<div class=\'sub-header\'> ");
document.writeln("		<div class=\'inner\'> ");
document.writeln(" 			<p class=\'sub-header-left\'>");
document.writeln("				威高梨花医疗美容：国内正规医疗美容品牌丨中韩合作");
document.writeln("			</p> ");

document.writeln(" 			<ul class=\'sub-header-right\'>");
document.writeln(" 				<li>");
document.writeln(" 					<a href=\'javascript:void(0)\' title=\'0631-5716999\'>");
document.writeln(" 						<i class=\'sub-icon\'></i><span>美丽热线</span>");
document.writeln(" 					</a>");
document.writeln(" 				</li>");
document.writeln(" 				<li class=\'relative\' id=\'gzpt\'>");
document.writeln(" 					<a href=\'javascript:void(0)\'>");
document.writeln(" 						<i class=\'sub-icon\'></i><span>公众平台</span><span class=\'wechat_png absolute\'></span>");
document.writeln(" 					</a>");
document.writeln(" 				</li>");
document.writeln(" 				<li>");
document.writeln(" 					<a href=\'javascript:void(0)\'>");
document.writeln(" 						<i class=\'sub-icon\'></i><span>官方微博</span>");
document.writeln(" 					</a>");
document.writeln(" 				</li>");
document.writeln(" 				<li>");
document.writeln(" 					<a href=\'/special/address\'>");
document.writeln(" 						<i class=\'sub-icon\'></i><span>来院地址</span>");
document.writeln(" 					</a>");
document.writeln(" 				</li>");
document.writeln(" 			</ul>");
document.writeln(" 		</div>");
document.writeln(" 	</div>");
document.writeln(" 	<div class=\'sub-header-nav\'>");
document.writeln(" 		<div class=\'inner\'>");
document.writeln(" 			<a href='\'/'\'><h1 class=\'logo\'>威高梨花医疗美容</h1></a>");
document.writeln(" 			<ul class=\'sub-nav\'>");
document.writeln(" 				<li>");
document.writeln(" 					<a href=\'/\'>首页</a>");
document.writeln(" 				</li>");
document.writeln(" 				<li>");
document.writeln(" 					<a href=\'/special/pp\'>品牌中心</a>");
document.writeln(" 				</li>");
document.writeln(" 				<li class=\'relative prom\'>");
document.writeln(" 					<a href=\'javascript:void(0)\' onclick=\'openZoosUrl();return false;\'>项目中心</a>");
document.writeln(" 				</li>");
document.writeln(" 				<li>");
document.writeln(" 					<a href=\'javascript:void(0)\' onclick=\'openZoosUrl();return false;\'>专家介绍</a>");
document.writeln(" 				</li>");
document.writeln(" 				<li>");
document.writeln(" 					<a href=\'javascript:void(0)\' onclick=\'openZoosUrl();return false;\'>真实案例</a>");
document.writeln(" 				</li>");
document.writeln(" 			</ul>");
document.writeln(" 		</div>");
document.writeln(" 	</div>");
document.writeln(" </div>");
document.writeln(" <script type=\'text/javascript\' src=\'/style/js/index.js\'></script>");